# Generated by Django 5.0 on 2024-01-02 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='Site Name')),
                ('site_url', models.URLField(help_text='https://sitename.com/', verbose_name='Site URL')),
                ('site_owner_name', models.CharField(max_length=50, verbose_name='Site Owner Name')),
                ('about_site', models.TextField(verbose_name='About of Site')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Phone', max_length=50, verbose_name='contact name')),
                ('value', models.CharField(max_length=100, verbose_name='09111111111')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_settings_app.setting', verbose_name='setting')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='instagram', max_length=50, verbose_name='Network Name')),
                ('url', models.URLField(help_text='https://instagram.com/username/')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_settings_app.setting', verbose_name='setting')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
    ]
