# Generated by Django 5.0 on 2024-01-02 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('send_date', models.DateTimeField(verbose_name='Send Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Pending', max_length=50, verbose_name='Status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
