# Generated by Django 5.0 on 2024-01-02 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories_app', '0001_initial'),
        ('tags_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product Title')),
                ('slug', models.SlugField(help_text='sample-title-slug', verbose_name='Product Slug')),
                ('short_description', models.CharField(max_length=150, verbose_name='Product Short Description')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('visit_count', models.IntegerField(default=0, verbose_name='Product Visitors Count')),
                ('created_date', models.DateTimeField(verbose_name='Product Created Date')),
                ('published_date', models.DateTimeField(verbose_name='Product Published Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Pending', max_length=50, verbose_name='Product Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories_app.category', verbose_name='Product Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('tags', models.ManyToManyField(to='tags_app.tag', verbose_name='Product Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
