# Generated by Django 5.0 on 2024-01-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_gallery_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='ProductGallery',
        ),
    ]
