# Generated by Django 5.0 on 2024-01-03 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_rename_gallery_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='galleries', to='products_app.product'),
            preserve_default=False,
        ),
    ]
